[package]
name = "yggdrasil"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.14.2", features = ["wayland"] }
bevy_rapier3d = { version = "0.27.0", features = ["debug-render-3d", "simd-stable"] }
