[package]
name = "ysync"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_math = "0.14.2"
strum = { version = "0.26.3", features = ["derive"] }
tokio = { version = "1.40.0", features = ["net", "rt", "sync"] }
